// <auto-generated />
namespace Study.SharedMigrationsWithTeam.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Campo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campo2));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011526402_Campo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
